# Generated by Django 4.1.4 on 2022-12-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_comentary_task_comentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentary',
            name='task_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentary',
            name='comentary_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
