# Generated by Django 4.1.4 on 2022-12-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_comentary_task_id_alter_comentary_comentary_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentary',
            name='task_id',
        ),
    ]
